// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lbm/fswap/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/Finschia/finschia-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// constant value representing the exchange rate, without decimal (148079656)
	SwapRate uint64 `protobuf:"varint,1,opt,name=swap_rate,json=swapRate,proto3" json:"swap_rate,omitempty"`
	// The number shows how to get the true exchange rate by dividing swap_rate by 10 to the power
	SwapRateDecimals int32 `protobuf:"varint,2,opt,name=swap_rate_decimals,json=swapRateDecimals,proto3" json:"swap_rate_decimals,omitempty"`
	// new denomination for new coin after swap
	NewCoinDenom string `protobuf:"bytes,3,opt,name=new_coin_denom,json=newCoinDenom,proto3" json:"new_coin_denom,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_15e620b81032c44d, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSwapRate() uint64 {
	if m != nil {
		return m.SwapRate
	}
	return 0
}

func (m *Params) GetSwapRateDecimals() int32 {
	if m != nil {
		return m.SwapRateDecimals
	}
	return 0
}

func (m *Params) GetNewCoinDenom() string {
	if m != nil {
		return m.NewCoinDenom
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "lbm.fswap.v1.Params")
}

func init() { proto.RegisterFile("lbm/fswap/v1/params.proto", fileDescriptor_15e620b81032c44d) }

var fileDescriptor_15e620b81032c44d = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x31, 0x4b, 0xc4, 0x30,
	0x18, 0x86, 0x1b, 0x3d, 0x0f, 0xaf, 0x1c, 0x22, 0xc5, 0xa1, 0x9e, 0x10, 0x8b, 0x38, 0x74, 0xd0,
	0x86, 0xe2, 0xe6, 0xa8, 0x87, 0x38, 0x4a, 0x47, 0x97, 0x92, 0xb4, 0xb9, 0x5e, 0xb0, 0xc9, 0x57,
	0x9a, 0xd8, 0xea, 0xe4, 0x5f, 0x70, 0x74, 0xf4, 0xe7, 0x38, 0xde, 0xe8, 0x28, 0xed, 0x1f, 0x91,
	0xf4, 0xaa, 0xdb, 0xcb, 0xf3, 0xbc, 0xbc, 0x21, 0x9f, 0x7b, 0x5c, 0x32, 0x49, 0x56, 0xba, 0xa5,
	0x15, 0x69, 0x62, 0x52, 0xd1, 0x9a, 0x4a, 0x1d, 0x55, 0x35, 0x18, 0xf0, 0xe6, 0x25, 0x93, 0xd1,
	0xa0, 0xa2, 0x26, 0x5e, 0x1c, 0x15, 0x50, 0xc0, 0x20, 0x88, 0x4d, 0xdb, 0xce, 0x02, 0x67, 0xa0,
	0x25, 0x68, 0xc2, 0xa8, 0xe6, 0xa4, 0x89, 0x19, 0x37, 0x34, 0x26, 0x19, 0x08, 0xb5, 0xf5, 0x67,
	0x6f, 0xee, 0xf4, 0x61, 0xd8, 0xf4, 0x4e, 0xdc, 0x99, 0x9d, 0x4a, 0x6b, 0x6a, 0xb8, 0x8f, 0x02,
	0x14, 0x4e, 0x92, 0x7d, 0x0b, 0x12, 0x6a, 0xb8, 0x77, 0xe1, 0x7a, 0xff, 0x32, 0xcd, 0x79, 0x26,
	0x24, 0x2d, 0xb5, 0xbf, 0x13, 0xa0, 0x70, 0x2f, 0x39, 0xfc, 0x6b, 0x2d, 0x47, 0xee, 0x9d, 0xbb,
	0x07, 0x8a, 0xb7, 0xa9, 0x7d, 0x26, 0xcd, 0xb9, 0x02, 0xe9, 0xef, 0x06, 0x28, 0x9c, 0x25, 0x73,
	0xc5, 0xdb, 0x5b, 0x10, 0x6a, 0x69, 0xd9, 0xf5, 0xe4, 0xe3, 0xf3, 0xd4, 0xb9, 0xb9, 0xff, 0xea,
	0x30, 0xda, 0x74, 0x18, 0xfd, 0x74, 0x18, 0xbd, 0xf7, 0xd8, 0xd9, 0xf4, 0xd8, 0xf9, 0xee, 0xb1,
	0xf3, 0x18, 0x15, 0xc2, 0xac, 0x9f, 0x59, 0x94, 0x81, 0x24, 0x77, 0x42, 0xe9, 0x6c, 0x2d, 0x28,
	0x59, 0x8d, 0xe1, 0x52, 0xe7, 0x4f, 0xe4, 0x65, 0x3c, 0x8c, 0x79, 0xad, 0xb8, 0x66, 0xd3, 0xe1,
	0x47, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x75, 0x83, 0xcb, 0xd2, 0x32, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewCoinDenom) > 0 {
		i -= len(m.NewCoinDenom)
		copy(dAtA[i:], m.NewCoinDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.NewCoinDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SwapRateDecimals != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SwapRateDecimals))
		i--
		dAtA[i] = 0x10
	}
	if m.SwapRate != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SwapRate))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SwapRate != 0 {
		n += 1 + sovParams(uint64(m.SwapRate))
	}
	if m.SwapRateDecimals != 0 {
		n += 1 + sovParams(uint64(m.SwapRateDecimals))
	}
	l = len(m.NewCoinDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapRate", wireType)
			}
			m.SwapRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SwapRate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapRateDecimals", wireType)
			}
			m.SwapRateDecimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SwapRateDecimals |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
