# Verify that generated code is up-to-date.

name: Check generated code
on: push
  # workflow_dispatch:
  # pull_request:
  #   branches:
  #     - '*'

permissions:
  contents: read

jobs:
  check-error-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Check generated swagger docs
        run: |
          go run ./tools/error_doc
          if ! git diff --stat --exit-code ; then
            echo ">> ERROR:"
            echo ">>"
            echo ">> Generated mocks require update (either Mockery or source files may have changed)."
            echo ">> Ensure your tools are up-to-date, re-run 'make mockery' and update this PR."
            echo ">>"
            exit 1
          fi