# Verify that generated code is up-to-date.

name: Check generated code
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  check-error-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Check generated error docs
        run: |
          cd ./tools/error_doc
          go run ./
          if ! git diff --stat --exit-code ; then
            echo ">> ERROR:"
            echo ">>"
            echo ">> Error documents require update (source files in x folder may have changed)."
            echo ">> Ensure your tools are up-to-date, re-run 'go run ./' in tools/error_doc and update this PR."
            echo ">>"
            exit 1
          fi
